version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.2.1"

    steps:
      - checkout

      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: pod install
          working_directory: Example

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: fastlane scan
          working_directory: Example
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: Blockstack-Example
            SCAN_OUTPUT_DIRECTORY: ./test_output
            SCAN_OUTPUT_TYPES: junit
            SCAN_OUTPUT_FILES: report.xml

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: "./Example/test_output"
      - store_artifacts:
          path: "./Example/test_output"
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
